In [1]:
import pandas as pd
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()

In [3]:
import numpy as np

In [4]:
X=digits.data
y=digits.target

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
lr=LogisticRegression()

In [9]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [10]:
from sklearn import model_selection

In [12]:
Kfold=model_selection.KFold(n_splits=10,random_state=7)

In [15]:
results=model_selection.cross_val_score(lr,X,y,cv=Kfold,scoring='accuracy')

In [17]:
print(("Accuracy: %.3f (%.3f)")%(results.mean(),results.std()))

Accuracy: 0.932 (0.035)


In [18]:
results=model_selection.cross_val_score(lr,X,y,cv=Kfold,scoring='neg_log_loss')

In [19]:
print(("LogLoss: %.3f (%.3f)")%(results.mean(),results.std()))

LogLoss: -0.344 (0.220)


In [20]:
results=model_selection.cross_val_score(lr,X,y,cv=Kfold,scoring='r2_score')

ValueError: 'r2_score' is not a valid scoring value. Valid options are ['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'mutual_info_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'v_measure_score']

In [24]:
y_pred=lr.predict(X)

In [25]:
from sklearn.metrics import r2_score

In [26]:
r2_score(y,y_pred)

0.9481183526763202

In [27]:
results=model_selection.cross_val_score(lr,X,y,cv=Kfold,scoring='neg_mean_absolute_error')

In [28]:
print(("MAE: %.3f (%.3f)")%(results.mean(),results.std()))

MAE: -0.277 (0.144)


In [29]:
results=model_selection.cross_val_score(lr,X,y,cv=Kfold,scoring='neg_mean_squared_error')

In [30]:
print(("MSE: %.3f (%.3f)")%(results.mean(),results.std()))

MSE: -1.452 (0.805)


In [31]:
from sklearn.metrics import confusion_matrix

In [33]:
predicted=lr.predict(X_test)

In [34]:
matrix=confusion_matrix(y_test,predicted)

In [35]:
print(matrix)

[[52  0  0  0  1  0  0  0  0  0]
 [ 0 43  1  0  0  0  0  0  6  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  1  0  0  1  0]
 [ 0  1  0  0 59  0  0  0  0  0]
 [ 0  2  1  0  0 61  0  1  1  0]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  1  0  0  0  1  0  0 41  0]
 [ 0  0  0  0  0  0  0  0  5 54]]


In [36]:
from sklearn.metrics import classification_report

In [39]:
report=classification_report(y_test,predicted)

In [40]:
print(report)

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        53
          1       0.91      0.86      0.89        50
          2       0.96      1.00      0.98        47
          3       1.00      0.96      0.98        54
          4       0.98      0.98      0.98        60
          5       0.95      0.92      0.94        66
          6       1.00      0.98      0.99        53
          7       0.98      0.98      0.98        55
          8       0.76      0.95      0.85        43
          9       0.98      0.92      0.95        59

avg / total       0.96      0.95      0.95       540

